version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booksdb
    volumes:
      - ./src/data:/docker-entrypoint-initdb.d  # Mount the src/data folder to the container
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 3002:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  react-app:
    build: .
    container_name: react_app
    ports:
      - "3001:3001"
      - "5800:5800"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgadmin:
